from typing import Any, Dict, List, Optional, Protocol


class ListaPrecioGateway(Protocol):
    def list(self) -> List[Dict[str, Any]]: ...

    def get(self, lista_precio_id: int) -> Optional[Dict[str, Any]]: ...

    def create(self, data: Dict[str, Any]) -> Dict[str, Any]: ...

    def update(
        self, lista_precio_id: int, data: Dict[str, Any]
    ) -> Optional[Dict[str, Any]]: ...

    def patch(
        self, lista_precio_id: int, data: Dict[str, Any]
    ) -> Optional[Dict[str, Any]]: ...

    def delete(self, lista_precio_id: int) -> bool: ...
