from typing import Any, Dict, List, Optional, Protocol


class ProductoGateway(Protocol):
    def list(self) -> List[Dict[str, Any]]: ...

    def get(self, producto_id: int) -> Optional[Dict[str, Any]]: ...

    def create(self, data: Dict[str, Any]) -> Dict[str, Any]: ...

    def update(
        self, producto_id: int, data: Dict[str, Any]
    ) -> Optional[Dict[str, Any]]: ...

    def delete(self, producto_id: int) -> bool: ...
